name = "PilotComnad"
modname = "SPC"
mainprefix = "dcd"
prefix = "dcd_spc"
author = "DCD"
sig_version = 3
version = "0.0.01"
reuse_private_key = false
files = [
    "mod.cpp",
    "LICENSE.md"
]
include = [
    "include/*"
]

key_name = "{{prefix}}_{{version}}"
authority = "{{prefix}}_{{version}}"

releasebuild = [
    #"!cpModcpps",
    "@zip @{{modname}}_{{version}}"
]
